import { db, productsTable } from "@workspace/db";
import { logger } from "./logger";

const DEFAULT_PRODUCTS = [
  {
    id: "1",
    name: "Casamigos Blanco Tequila",
    shortName: "Casamigos Blanco",
    category: "tequila",
    price: 112350,
    rating: 4.8,
    reviewCount: 312,
    description:
      "Casamigos Blanco is a premium unaged tequila crafted from carefully selected 100% blue Weber agave grown in the highlands of Jalisco, Mexico. Slow-roasted and fermented to produce a clean, crisp tequila with a smooth and refreshing flavor profile. Bright notes of citrus, sweet agave, and subtle hints of vanilla — finishing smooth and well-balanced.",
    shortDescription:
      "Crisp and smooth premium tequila from 100% blue Weber agave. Fresh citrus notes, light sweetness, perfect for sipping or cocktails.",
    ingredients: [
      "100% Blue Weber Agave",
      "Jalisco Highland Water",
      "Citrus Notes",
      "Vanilla Hints",
    ],
    sizes: [
      { label: "750ml", price: 112350 },
      { label: "1 Litre", price: 148000 },
    ],
    imageUri:
      "https://authenticshayolockerr.com/wp-content/uploads/2026/03/Casamigos-Blanco-Tequila-Bottle-1024x1024.webp",
    imageColor: "#1a3040",
    accentColor: "#5ba3c9",
    featured: true,
    tags: ["bestseller", "premium"],
    origin: "Jalisco, Mexico",
    abv: "40%",
    sortOrder: 1,
  },
  {
    id: "2",
    name: "Casamigos Reposado Tequila",
    shortName: "Casamigos Reposado",
    category: "tequila",
    price: 118600,
    rating: 4.9,
    reviewCount: 278,
    description:
      "Casamigos Reposado is aged for 7 months in American white oak barrels, giving it a smooth caramel and cocoa complexity that sets it apart. Made from 100% blue Weber agave from the Jalisco highlands. Warm oak, caramel, and agave flavors come together in a perfectly balanced, sippable tequila that's as good neat as it is in a cocktail.",
    shortDescription:
      "Aged 7 months in American oak. Rich caramel, cocoa, and agave notes with exceptional smoothness.",
    ingredients: [
      "100% Blue Weber Agave",
      "Caramel",
      "Cocoa",
      "Oak Barrel Aged 7 Months",
    ],
    sizes: [
      { label: "750ml", price: 118600 },
      { label: "1 Litre", price: 158000 },
    ],
    imageUri:
      "https://authenticshayolockerr.com/wp-content/uploads/2026/03/Casamigos-Reposado-Tequila-Bottle-1024x1024.webp",
    imageColor: "#3d2810",
    accentColor: "#c9963a",
    featured: true,
    tags: ["popular", "aged"],
    origin: "Jalisco, Mexico",
    abv: "40%",
    sortOrder: 2,
  },
  {
    id: "3",
    name: "Clase Azul Añejo Tequila",
    shortName: "Clase Azul Añejo",
    category: "tequila",
    price: 362500,
    rating: 4.9,
    reviewCount: 145,
    description:
      "Clase Azul Añejo is an ultra-premium tequila aged for 25 months in sherry oak casks, yielding a remarkably complex spirit. Hand-crafted in Santa Maria Canchesdé, Oaxaca. Rich dried fruit, dark chocolate, cinnamon, and vanilla notes build into a long, warming finish. Presented in an iconic hand-painted ceramic decanter — a collectible as much as a spirit.",
    shortDescription:
      "Ultra-premium luxury tequila aged 25 months in sherry oak. Dark chocolate, dried fruit, and cinnamon in an iconic hand-painted decanter.",
    ingredients: [
      "100% Blue Weber Agave",
      "Sherry Oak Aged 25 Months",
      "Dark Chocolate",
      "Dried Fruit",
      "Cinnamon",
    ],
    sizes: [{ label: "750ml", price: 362500 }],
    imageUri:
      "https://authenticshayolockerr.com/wp-content/uploads/2026/03/Clase-Azul-Anejo-Tequila-Bottle-1024x1024.webp",
    imageColor: "#1a0d00",
    accentColor: "#d4a843",
    featured: true,
    tags: ["luxury", "limited"],
    origin: "Oaxaca, Mexico",
    abv: "40%",
    sortOrder: 3,
  },
  {
    id: "4",
    name: "Clase Azul Reposado Tequila",
    shortName: "Clase Azul Reposado",
    category: "tequila",
    price: 362500,
    rating: 4.8,
    reviewCount: 198,
    description:
      "Clase Azul Reposado is a handcrafted ultra-premium tequila aged for 8 months in American oak whisky barrels. Produced from 100% organic agave tequilana Weber Blue, it delivers an exceptionally smooth and complex profile with notes of vanilla, coconut, cinnamon, and apple. The iconic hand-painted ceramic bottle makes it as much a work of art as a world-class spirit.",
    shortDescription:
      "Handcrafted and aged 8 months in whisky barrels. Vanilla, coconut, and cinnamon notes in an iconic ceramic bottle.",
    ingredients: [
      "100% Organic Agave Weber Blue",
      "American Oak Aged 8 Months",
      "Vanilla",
      "Coconut",
      "Cinnamon",
    ],
    sizes: [{ label: "750ml", price: 362500 }],
    imageUri:
      "https://authenticshayolockerr.com/wp-content/uploads/2026/03/Clase-Azul-Reposado-Tequila-Bottle-1024x1024.webp",
    imageColor: "#0d1a2a",
    accentColor: "#4a90c8",
    featured: false,
    tags: ["luxury", "artisan"],
    origin: "Jalisco, Mexico",
    abv: "40%",
    sortOrder: 4,
  },
  {
      id: "5",
      name: "Patron Anejo Tequila",
      shortName: "Patron Anejo",
      category: "tequila",
      price: 125900,
      rating: 4.5,
      reviewCount: 0,
      description: "Patron Anejo Tequila — Aged in oak barrels for a smooth, refined finish. Sourced authentic and verified by Authentic Shayo Lockerr.",
      shortDescription: "Aged in oak barrels for a smooth, refined finish.",
      ingredients: [],
      sizes: [{ label: "750ml", price: 125900 }],
      imageUri: "",
      imageColor: "#2c3a1c",
      accentColor: "#a8c66c",
      featured: false,
      tags: [],
      origin: "Jalisco, Mexico",
      abv: "40%",
      sortOrder: 5,
    },
  {
      id: "6",
      name: "Patron Reposado Tequila",
      shortName: "Patron Reposado",
      category: "tequila",
      price: 125900,
      rating: 4.5,
      reviewCount: 0,
      description: "Patron Reposado Tequila — Rested in oak for balanced agave and oak character. Sourced authentic and verified by Authentic Shayo Lockerr.",
      shortDescription: "Rested in oak for balanced agave and oak character.",
      ingredients: [],
      sizes: [{ label: "750ml", price: 125900 }],
      imageUri: "",
      imageColor: "#2c3a1c",
      accentColor: "#c9b037",
      featured: false,
      tags: [],
      origin: "Jalisco, Mexico",
      abv: "40%",
      sortOrder: 6,
    },
  {
      id: "7",
      name: "Johnnie Walker Blue Label",
      shortName: "JW Blue Label",
      category: "tequila",
      price: 250000,
      rating: 4.5,
      reviewCount: 0,
      description: "Johnnie Walker Blue Label — An exceptionally smooth, rare blended Scotch whisky. Sourced authentic and verified by Authentic Shayo Lockerr.",
      shortDescription: "An exceptionally smooth, rare blended Scotch whisky.",
      ingredients: [],
      sizes: [{ label: "750ml", price: 250000 }],
      imageUri: "",
      imageColor: "#2c3a1c",
      accentColor: "#8bb04a",
      featured: false,
      tags: ["premium"],
      origin: "Scotland",
      abv: "40%",
      sortOrder: 7,
    },
  {
      id: "8",
      name: "El Padrino Tequila",
      shortName: "El Padrino",
      category: "tequila",
      price: 112350,
      rating: 4.5,
      reviewCount: 0,
      description: "El Padrino Tequila — Smooth premium tequila with bright agave notes. Sourced authentic and verified by Authentic Shayo Lockerr.",
      shortDescription: "Smooth premium tequila with bright agave notes.",
      ingredients: [],
      sizes: [{ label: "750ml", price: 112350 }],
      imageUri: "",
      imageColor: "#2c3a1c",
      accentColor: "#a8c66c",
      featured: false,
      tags: [],
      origin: "Mexico",
      abv: "40%",
      sortOrder: 8,
    },
  {
      id: "9",
      name: "Ellington Whisky",
      shortName: "Ellington",
      category: "whiskey",
      price: 69400,
      rating: 4.5,
      reviewCount: 0,
      description: "Ellington Whisky — Smooth blended whisky, easy sipping. Sourced authentic and verified by Authentic Shayo Lockerr.",
      shortDescription: "Smooth blended whisky, easy sipping.",
      ingredients: [],
      sizes: [{ label: "750ml", price: 69400 }],
      imageUri: "",
      imageColor: "#3a2410",
      accentColor: "#c9883f",
      featured: false,
      tags: [],
      origin: "Scotland",
      abv: "40%",
      sortOrder: 9,
    },
  {
      id: "10",
      name: "Kil Brin Whisky",
      shortName: "Kil Brin",
      category: "whiskey",
      price: 69400,
      rating: 4.5,
      reviewCount: 0,
      description: "Kil Brin Whisky — Mellow blended whisky with a clean finish. Sourced authentic and verified by Authentic Shayo Lockerr.",
      shortDescription: "Mellow blended whisky with a clean finish.",
      ingredients: [],
      sizes: [{ label: "750ml", price: 69400 }],
      imageUri: "",
      imageColor: "#3a2410",
      accentColor: "#b5742c",
      featured: false,
      tags: [],
      origin: "Scotland",
      abv: "40%",
      sortOrder: 10,
    },
  {
      id: "11",
      name: "Shieldaig 12 Years",
      shortName: "Shieldaig 12yr",
      category: "whiskey",
      price: 104300,
      rating: 4.5,
      reviewCount: 0,
      description: "Shieldaig 12 Years — Aged 12 years for depth and warmth. Sourced authentic and verified by Authentic Shayo Lockerr.",
      shortDescription: "Aged 12 years for depth and warmth.",
      ingredients: [],
      sizes: [{ label: "750ml", price: 104300 }],
      imageUri: "",
      imageColor: "#3a2410",
      accentColor: "#e0a45a",
      featured: false,
      tags: [],
      origin: "Scotland",
      abv: "40%",
      sortOrder: 11,
    },
  {
      id: "12",
      name: "Shieldaig Blended Malt",
      shortName: "Shieldaig Malt",
      category: "whiskey",
      price: 104300,
      rating: 4.5,
      reviewCount: 0,
      description: "Shieldaig Blended Malt — Rich blended malt with rounded flavour. Sourced authentic and verified by Authentic Shayo Lockerr.",
      shortDescription: "Rich blended malt with rounded flavour.",
      ingredients: [],
      sizes: [{ label: "750ml", price: 104300 }],
      imageUri: "",
      imageColor: "#3a2410",
      accentColor: "#a9651f",
      featured: false,
      tags: [],
      origin: "Scotland",
      abv: "40%",
      sortOrder: 12,
    },
  {
      id: "13",
      name: "The Glenlivet Founder's Reserve",
      shortName: "Glenlivet Founder's",
      category: "whiskey",
      price: 138800,
      rating: 4.5,
      reviewCount: 0,
      description: "The Glenlivet Founder's Reserve — Classic Speyside single malt, smooth and fruity. Sourced authentic and verified by Authentic Shayo Lockerr.",
      shortDescription: "Classic Speyside single malt, smooth and fruity.",
      ingredients: [],
      sizes: [{ label: "750ml", price: 138800 }],
      imageUri: "",
      imageColor: "#3a2410",
      accentColor: "#c9883f",
      featured: false,
      tags: [],
      origin: "Speyside, Scotland",
      abv: "40%",
      sortOrder: 13,
    },
  {
      id: "14",
      name: "Glen Fohdry 12 Years",
      shortName: "Glen Fohdry 12yr",
      category: "whiskey",
      price: 104300,
      rating: 4.5,
      reviewCount: 0,
      description: "Glen Fohdry 12 Years — Aged 12 years, balanced and smooth. Sourced authentic and verified by Authentic Shayo Lockerr.",
      shortDescription: "Aged 12 years, balanced and smooth.",
      ingredients: [],
      sizes: [{ label: "750ml", price: 104300 }],
      imageUri: "",
      imageColor: "#3a2410",
      accentColor: "#b5742c",
      featured: false,
      tags: [],
      origin: "Scotland",
      abv: "40%",
      sortOrder: 14,
    },
  {
      id: "15",
      name: "Glen Fohdry Fion Frangach",
      shortName: "Glen Fohdry FF",
      category: "whiskey",
      price: 104300,
      rating: 4.5,
      reviewCount: 0,
      description: "Glen Fohdry Fion Frangach — Wine-cask influenced malt with character. Sourced authentic and verified by Authentic Shayo Lockerr.",
      shortDescription: "Wine-cask influenced malt with character.",
      ingredients: [],
      sizes: [{ label: "750ml", price: 104300 }],
      imageUri: "",
      imageColor: "#3a2410",
      accentColor: "#e0a45a",
      featured: false,
      tags: [],
      origin: "Scotland",
      abv: "40%",
      sortOrder: 15,
    },
  {
      id: "16",
      name: "Red Bush Whiskey",
      shortName: "Red Bush",
      category: "whiskey",
      price: 69400,
      rating: 4.5,
      reviewCount: 0,
      description: "Red Bush Whiskey — Smooth Irish-style whiskey, lightly sweet. Sourced authentic and verified by Authentic Shayo Lockerr.",
      shortDescription: "Smooth Irish-style whiskey, lightly sweet.",
      ingredients: [],
      sizes: [{ label: "750ml", price: 69400 }],
      imageUri: "",
      imageColor: "#3a2410",
      accentColor: "#a9651f",
      featured: false,
      tags: [],
      origin: "Ireland",
      abv: "40%",
      sortOrder: 16,
    },
  {
      id: "17",
      name: "Ensign Red Whisky",
      shortName: "Ensign Red",
      category: "whiskey",
      price: 69400,
      rating: 4.5,
      reviewCount: 0,
      description: "Ensign Red Whisky — Approachable blended whisky. Sourced authentic and verified by Authentic Shayo Lockerr.",
      shortDescription: "Approachable blended whisky.",
      ingredients: [],
      sizes: [{ label: "750ml", price: 69400 }],
      imageUri: "",
      imageColor: "#3a2410",
      accentColor: "#c9883f",
      featured: false,
      tags: [],
      origin: "Scotland",
      abv: "40%",
      sortOrder: 17,
    },
  {
      id: "18",
      name: "Grange Stone Big",
      shortName: "Grange Stone Big",
      category: "whiskey",
      price: 208200,
      rating: 4.5,
      reviewCount: 0,
      description: "Grange Stone Big — Premium large-format whisky. Sourced authentic and verified by Authentic Shayo Lockerr.",
      shortDescription: "Premium large-format whisky.",
      ingredients: [],
      sizes: [{ label: "750ml", price: 208200 }],
      imageUri: "",
      imageColor: "#3a2410",
      accentColor: "#b5742c",
      featured: false,
      tags: ["premium"],
      origin: "Scotland",
      abv: "40%",
      sortOrder: 18,
    },
  {
      id: "19",
      name: "Grange Stone",
      shortName: "Grange Stone",
      category: "whiskey",
      price: 104300,
      rating: 4.5,
      reviewCount: 0,
      description: "Grange Stone — Smooth blended whisky. Sourced authentic and verified by Authentic Shayo Lockerr.",
      shortDescription: "Smooth blended whisky.",
      ingredients: [],
      sizes: [{ label: "750ml", price: 104300 }],
      imageUri: "",
      imageColor: "#3a2410",
      accentColor: "#e0a45a",
      featured: false,
      tags: [],
      origin: "Scotland",
      abv: "40%",
      sortOrder: 19,
    },
  {
      id: "20",
      name: "Mash Cut Whisky",
      shortName: "Mash Cut",
      category: "whiskey",
      price: 69400,
      rating: 4.5,
      reviewCount: 0,
      description: "Mash Cut Whisky — Crafted blend with a clean finish. Sourced authentic and verified by Authentic Shayo Lockerr.",
      shortDescription: "Crafted blend with a clean finish.",
      ingredients: [],
      sizes: [{ label: "750ml", price: 69400 }],
      imageUri: "",
      imageColor: "#3a2410",
      accentColor: "#a9651f",
      featured: false,
      tags: [],
      origin: "Scotland",
      abv: "40%",
      sortOrder: 20,
    },
  {
      id: "21",
      name: "Bond Stone Whisky",
      shortName: "Bond Stone",
      category: "whiskey",
      price: 69400,
      rating: 4.5,
      reviewCount: 0,
      description: "Bond Stone Whisky — Smooth everyday blended whisky. Sourced authentic and verified by Authentic Shayo Lockerr.",
      shortDescription: "Smooth everyday blended whisky.",
      ingredients: [],
      sizes: [{ label: "750ml", price: 69400 }],
      imageUri: "",
      imageColor: "#3a2410",
      accentColor: "#c9883f",
      featured: false,
      tags: [],
      origin: "Scotland",
      abv: "40%",
      sortOrder: 21,
    },
  {
      id: "22",
      name: "Isle of Skye 8 Years",
      shortName: "Isle of Skye 8yr",
      category: "whiskey",
      price: 69400,
      rating: 4.5,
      reviewCount: 0,
      description: "Isle of Skye 8 Years — Island blend aged 8 years. Sourced authentic and verified by Authentic Shayo Lockerr.",
      shortDescription: "Island blend aged 8 years.",
      ingredients: [],
      sizes: [{ label: "750ml", price: 69400 }],
      imageUri: "",
      imageColor: "#3a2410",
      accentColor: "#b5742c",
      featured: false,
      tags: [],
      origin: "Isle of Skye, Scotland",
      abv: "40%",
      sortOrder: 22,
    },
  {
      id: "23",
      name: "Fordhamlee Whisky",
      shortName: "Fordhamlee",
      category: "whiskey",
      price: 69400,
      rating: 4.5,
      reviewCount: 0,
      description: "Fordhamlee Whisky — Smooth blended whisky. Sourced authentic and verified by Authentic Shayo Lockerr.",
      shortDescription: "Smooth blended whisky.",
      ingredients: [],
      sizes: [{ label: "750ml", price: 69400 }],
      imageUri: "",
      imageColor: "#3a2410",
      accentColor: "#e0a45a",
      featured: false,
      tags: [],
      origin: "Scotland",
      abv: "40%",
      sortOrder: 23,
    },
  {
      id: "24",
      name: "Shieldaig Finest Old",
      shortName: "Shieldaig Finest",
      category: "whiskey",
      price: 104300,
      rating: 4.5,
      reviewCount: 0,
      description: "Shieldaig Finest Old — Finest old blend, mellow and rich. Sourced authentic and verified by Authentic Shayo Lockerr.",
      shortDescription: "Finest old blend, mellow and rich.",
      ingredients: [],
      sizes: [{ label: "750ml", price: 104300 }],
      imageUri: "",
      imageColor: "#3a2410",
      accentColor: "#a9651f",
      featured: false,
      tags: [],
      origin: "Scotland",
      abv: "40%",
      sortOrder: 24,
    },
  {
      id: "25",
      name: "Isle of Skye 12 Years",
      shortName: "Isle of Skye 12yr",
      category: "whiskey",
      price: 104300,
      rating: 4.5,
      reviewCount: 0,
      description: "Isle of Skye 12 Years — Island blend aged 12 years. Sourced authentic and verified by Authentic Shayo Lockerr.",
      shortDescription: "Island blend aged 12 years.",
      ingredients: [],
      sizes: [{ label: "750ml", price: 104300 }],
      imageUri: "",
      imageColor: "#3a2410",
      accentColor: "#c9883f",
      featured: false,
      tags: [],
      origin: "Isle of Skye, Scotland",
      abv: "40%",
      sortOrder: 25,
    },
  {
      id: "26",
      name: "Isle of Skye 18 Years",
      shortName: "Isle of Skye 18yr",
      category: "whiskey",
      price: 208200,
      rating: 4.5,
      reviewCount: 0,
      description: "Isle of Skye 18 Years — Premium island blend aged 18 years. Sourced authentic and verified by Authentic Shayo Lockerr.",
      shortDescription: "Premium island blend aged 18 years.",
      ingredients: [],
      sizes: [{ label: "750ml", price: 208200 }],
      imageUri: "",
      imageColor: "#3a2410",
      accentColor: "#b5742c",
      featured: false,
      tags: ["premium"],
      origin: "Isle of Skye, Scotland",
      abv: "40%",
      sortOrder: 26,
    },
  {
      id: "27",
      name: "Glenfiddich 14 Years",
      shortName: "Glenfiddich 14yr",
      category: "whiskey",
      price: 70000,
      rating: 4.5,
      reviewCount: 0,
      description: "Glenfiddich 14 Years — Speyside single malt aged 14 years. Sourced authentic and verified by Authentic Shayo Lockerr.",
      shortDescription: "Speyside single malt aged 14 years.",
      ingredients: [],
      sizes: [{ label: "750ml", price: 70000 }],
      imageUri: "",
      imageColor: "#3a2410",
      accentColor: "#e0a45a",
      featured: false,
      tags: [],
      origin: "Speyside, Scotland",
      abv: "40%",
      sortOrder: 27,
    },
  {
      id: "28",
      name: "Kaigan Whisky",
      shortName: "Kaigan",
      category: "whiskey",
      price: 69400,
      rating: 4.5,
      reviewCount: 0,
      description: "Kaigan Whisky — Smooth Japanese-style whisky. Sourced authentic and verified by Authentic Shayo Lockerr.",
      shortDescription: "Smooth Japanese-style whisky.",
      ingredients: [],
      sizes: [{ label: "750ml", price: 69400 }],
      imageUri: "",
      imageColor: "#3a2410",
      accentColor: "#a9651f",
      featured: false,
      tags: [],
      origin: "Japan",
      abv: "40%",
      sortOrder: 28,
    },
  {
      id: "29",
      name: "Crown Royal 2",
      shortName: "Crown Royal 2",
      category: "whiskey",
      price: 69400,
      rating: 4.5,
      reviewCount: 0,
      description: "Crown Royal 2 — Smooth Canadian-style blended whisky. Sourced authentic and verified by Authentic Shayo Lockerr.",
      shortDescription: "Smooth Canadian-style blended whisky.",
      ingredients: [],
      sizes: [{ label: "750ml", price: 69400 }],
      imageUri: "",
      imageColor: "#3a2410",
      accentColor: "#c9883f",
      featured: false,
      tags: [],
      origin: "Canada",
      abv: "40%",
      sortOrder: 29,
    },
  {
      id: "30",
      name: "Seven Sons Bourbon",
      shortName: "Seven Sons",
      category: "bourbon",
      price: 69400,
      rating: 4.5,
      reviewCount: 0,
      description: "Seven Sons Bourbon — Smooth bourbon with caramel and vanilla. Sourced authentic and verified by Authentic Shayo Lockerr.",
      shortDescription: "Smooth bourbon with caramel and vanilla.",
      ingredients: [],
      sizes: [{ label: "750ml", price: 69400 }],
      imageUri: "",
      imageColor: "#3d1c12",
      accentColor: "#d4843f",
      featured: false,
      tags: [],
      origin: "USA",
      abv: "40%",
      sortOrder: 30,
    },
  {
      id: "31",
      name: "Rough Rider Bourbon",
      shortName: "Rough Rider",
      category: "bourbon",
      price: 69400,
      rating: 4.5,
      reviewCount: 0,
      description: "Rough Rider Bourbon — Bold bourbon with rich oak notes. Sourced authentic and verified by Authentic Shayo Lockerr.",
      shortDescription: "Bold bourbon with rich oak notes.",
      ingredients: [],
      sizes: [{ label: "750ml", price: 69400 }],
      imageUri: "",
      imageColor: "#3d1c12",
      accentColor: "#c25b2c",
      featured: false,
      tags: [],
      origin: "USA",
      abv: "45%",
      sortOrder: 31,
    },
  {
      id: "32",
      name: "Tin Cup Bourbon",
      shortName: "Tin Cup",
      category: "bourbon",
      price: 69400,
      rating: 4.5,
      reviewCount: 0,
      description: "Tin Cup Bourbon — Rocky Mountain bourbon, smooth and spicy. Sourced authentic and verified by Authentic Shayo Lockerr.",
      shortDescription: "Rocky Mountain bourbon, smooth and spicy.",
      ingredients: [],
      sizes: [{ label: "750ml", price: 69400 }],
      imageUri: "",
      imageColor: "#3d1c12",
      accentColor: "#e09a52",
      featured: false,
      tags: [],
      origin: "USA",
      abv: "42%",
      sortOrder: 32,
    },
];

export async function seedProductsIfEmpty() {
  try {
    const existing = await db.select({ id: productsTable.id }).from(productsTable).limit(1);
    if (existing.length > 0) return;
    await db.insert(productsTable).values(DEFAULT_PRODUCTS);
    logger.info(`Seeded ${DEFAULT_PRODUCTS.length} default products`);
  } catch (err) {
    logger.error({ err }, "Failed to seed products");
  }
}
